# Generated by Django 3.1.6 on 2021-02-16 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('settlement', models.TextField(blank=True, null=True)),
                ('town', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('price', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('amenities', models.TextField(blank=True)),
                ('size', models.TextField(blank=True)),
                ('picture', models.TextField(blank=True)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.adress')),
            ],
        ),
    ]
